config/routes.rb
Rails.application.routes.draw do
  resources :topics
  resources :content_levels
  resources :content_types
  root 'dashboard#index'
  
  devise_for :users
  
	get 'explorer' => 'dashboard#explorer'
	get 'change_user_level' => 'dashboard#change_user_level'
	
	post 'set_user_level' => 'content_levels#set_user_level_setting', as: 'set_user_level'
  
  

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/content_level.rb
class ContentLevel < ActiveRecord::Base
	belongs_to :content_type
	has_many :topics
end

app/controllers/content_levels_controller.rb
class ContentLevelsController < ApplicationController
  before_action :set_content_level, only: [:show, :edit, :update, :destroy]

  # GET /content_levels
  # GET /content_levels.json
  def index
    @content_levels = ContentLevel.all.order(level: 'ASC')
  end

  # GET /content_levels/1
  # GET /content_levels/1.json
  def show
  end

  # GET /content_levels/new
  def new
	unless params[:content_type_id].nil?
		@content_type = ContentType.find(params[:content_type_id])
	end
    @content_level = ContentLevel.new
  end

  # GET /content_levels/1/edit
  def edit
	unless params[:content_type_id].nil?
		@content_type = ContentType.find(params[:content_type_id])
	end
  end

  # POST /content_levels
  # POST /content_levels.json
  def create
    @content_level = ContentLevel.new(content_level_params)

    respond_to do |format|
      if @content_level.save
        format.html { redirect_to @content_level, notice: 'Content level was successfully created.' }
        format.json { render :show, status: :created, location: @content_level }
      else
        format.html { render :new }
        format.json { render json: @content_level.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /content_levels/1
  # PATCH/PUT /content_levels/1.json
  def update
    respond_to do |format|
      if @content_level.update(content_level_params)
		 format.html { redirect_to content_levels_path, notice: 'Content level was successfully updated.' }
        format.json { render :show, status: :ok, location: @content_level }
      else
        format.html { render :edit }
        format.json { render json: @content_level.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /content_levels/1
  # DELETE /content_levels/1.json
  def destroy
    @content_level.destroy
    respond_to do |format|
      format.html { redirect_to content_levels_url, notice: 'Content level was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
	
	def set_user_level_setting
		session[:user_level_setting] = params[:user_level][:content_level_id]
		puts session[:user_level_setting]
		redirect_to explorer_path, notice: "#UserLevelIDSet: #{session[:user_level_setting].inspect}"
	end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_content_level
      @content_level = ContentLevel.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def content_level_params
      params.require(:content_level).permit(:name, :level, :shorted, :content_type_level_id)
    end
end

app/helpers/content_levels_helper.rb
module ContentLevelsHelper
end

app/views/content_levels/_form.html.erb
<%= simple_form_for @content_level do |f| %>
<%= f.text_field :content_type_level_id, as: :hidden, class: 'hidden form-control', value: @content_type.id unless @content_type.nil? %>
  <% if @content_level.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@content_level.errors.count, "error") %> prohibited this content_level from being saved:</h2>

      <ul>
      <% @content_level.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="col-sm-8">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: 'form-control' %>
    <%= f.label :level %><br>
    <%= f.number_field :level, class: 'form-control' %>
    <%= f.label :shorted %><br>
    <%= f.text_area :shorted, class: 'form-control' %>
	<br>
	<%= f.submit class: 'btn btn-primary' %>
</div>
<div class="row"></div>
<% end %>

app/views/content_levels/edit.html.erb
<h1>Editing Content Level</h1>

<%= render 'form' %>

app/views/content_levels/index.html.erb
<div class="content-actions pull-right">
	<%= link_to '<i class="fa fa-check"></i> New Content Level'.html_safe, new_content_level_path, class: 'btn' %>
</div>
<h2 class="page-header">Levels</h2>

<% @content_levels.each do |content_level| %>
	<div class="panel panel-black panel-widget col-sm-9">
		<div class="row no-padding">
			<div class="col-sm-3 col-lg-5 widget-left">
				<svg class="glyph stroked table"><use xlink:href="#stroked-table"/></svg>
			</div>
			<div class="col-sm-9 col-lg-7 widget-right">
				<div class="large"><%= content_level.name %></div>
				<div class="text-muted"><%= content_level.shorted %></div>
				<div class="form-group"></div>
				<ul><strong>Active Topics</strong>
					<% content_level.topics.each do |t| %>
					<li><%= link_to t.name, topic_path(t) %></li>
					<% end %>
					<% if content_level.topics.empty? %>
						<li class="text-danger">No active topics at this level.</li>
					<% end %>
				</ul>
				<div class="actions">
					<%#= link_to "<i class='fa fa-lightbulb-o'></i> New Topic for #{content_level.name}".html_safe, new_topic_path(:content_type_id => content_level.id) %>
					<%= link_to 'Show', content_level %> | 
					<%= link_to 'Edit', edit_content_level_path(content_level) %>
				</div>
			</div>
		</div>
	</div>
<% end %>

app/views/content_levels/new.html.erb
<h1>New Content Level</h1>

<%= render 'form' %>

<%= link_to 'Back', content_levels_path %>

app/views/content_levels/new.js.erb
$("#modal-window").html("<%= escape_javascript(render 'content_levels/form') %>");

app/views/content_levels/show.html.erb
<%= link_to 'Delete Level', @content_level, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger absolute-button' %>

<h2 class="page-header"><%= @content_level.name %></h2>
<p class="text-muted">
	<%= @content_level.shorted %>
</p>

<p>
  <strong>Name:</strong>
  <%= @content_level.name %>
</p>

<p>
  <strong>Level:</strong>
  <%= @content_level.level %>
</p>

<p>
  <strong>Shorted:</strong>
  <%= @content_level.shorted %>
</p>