config/routes.rb
Rails.application.routes.draw do
  resources :topics
  resources :content_levels
  resources :content_types
  root 'dashboard#index'
  
  devise_for :users
  
	get 'explorer' => 'dashboard#explorer'
	get 'change_user_level' => 'dashboard#change_user_level'
	
	post 'set_user_level' => 'content_levels#set_user_level_setting', as: 'set_user_level'
  
  

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/controllers/content_types_controller.rb
class ContentTypesController < ApplicationController
	before_action :set_content_type, only: [:show, :edit, :update, :destroy]
	before_action :color_selection, only: [:new, :edit, :update, :create]

  # GET /content_types
  # GET /content_types.json
  def index
    @content_types = ContentType.all
  end

  # GET /content_types/1
  # GET /content_types/1.json
  def show
  end

  # GET /content_types/new
  def new
    @content_type = ContentType.new
  end

  # GET /content_types/1/edit
  def edit
  end

  # POST /content_types
  # POST /content_types.json
  def create
    @content_type = ContentType.new(content_type_params)

    respond_to do |format|
      if @content_type.save
        format.html { redirect_to @content_type, notice: 'Content type was successfully created.' }
        format.json { render :show, status: :created, location: @content_type }
      else
        format.html { render :new }
        format.json { render json: @content_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /content_types/1
  # PATCH/PUT /content_types/1.json
  def update
    respond_to do |format|
      if @content_type.update(content_type_params)
        format.html { redirect_to @content_type, notice: 'Content type was successfully updated.' }
        format.json { render :show, status: :ok, location: @content_type }
      else
        format.html { render :edit }
        format.json { render json: @content_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /content_types/1
  # DELETE /content_types/1.json
  def destroy
    @content_type.destroy
    respond_to do |format|
      format.html { redirect_to content_types_url, notice: 'Content type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
	def color_selection
		@colors = ['Teal', 'Blue', 'Red', 'Orange', 'Black']
	end
    def set_content_type
      @content_type = ContentType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def content_type_params
		params.require(:content_type).permit(:name, :description, :color)
    end
end

app/helpers/content_types_helper.rb
module ContentTypesHelper
end

app/views/content_types/_form.html.erb
<%= simple_form_for @content_type do |f| %>
  <% if @content_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@content_type.errors.count, "error") %> prohibited this content_type from being saved:</h2>

      <ul>
      <% @content_type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class='form-group'>
    <%= f.label :name %><br>
    <%= f.text_field :name, class: 'form-control' %>
</div>
<div class='form-group'>
	<%= f.label :description %><br>
	<%= f.text_area :description, class: 'form-control' %>
</div>
<div class='form-group col-sm-6 row'>
	<%= f.label :color %><br>
	<%= f.select :color, @colors, {}, class: 'form-control' %>
</div>
<div class="form-group col-sm-12 row">
	<%= f.submit class: 'btn btn-primary' %>
</div>
<% end %>

app/views/content_types/edit.html.erb
<h2><%= "#{@content_type.name}"%><small> | Editing</small></h2>

<%= render 'form' %>

app/views/content_types/index.html.erb
<div class="content-actions pull-right">
	<%= link_to '<i class="fa fa-check"></i> New Content Type'.html_safe, new_content_type_path, class: 'btn' %>
</div>

<h2 class="page-header">Types</h2>

<% @content_types.each do |content_type| %>
	<div class="panel panel-<%=content_type.color.downcase %> panel-widget col-sm-9">
		<div class="row no-padding">
			<div class="col-sm-3 col-lg-5 widget-left">
				<svg class="glyph stroked blank document"><use xlink:href="#stroked-blank-document"/></svg>
			</div>
			<div class="col-sm-9 col-lg-7 widget-right">
				<div class="large"><%= content_type.name %></div>
				<div class="text-muted"><%= content_type.description %></div>
				<div class="form-group">
					<br>
					<%= link_to "<i class='fa fa-lightbulb-o'></i> New Topic for #{content_type.name}".html_safe, new_topic_path(:content_type_id => content_type.id) %>
				</div>
				<ul><strong>Active Topics</strong>
					<% content_type.topics.each do |t| %>
					<li><%= link_to t.name, topic_path(t) %></li>
					<% end %>
                    <% if content_type.topics.empty? %>
                        <li class="text-danger">No active topics for this type.</li>
                    <% end %>
				</ul>
				<div class="actions">
					<%= link_to 'Show', content_type %> | 
					<%= link_to 'Edit', edit_content_type_path(content_type) %>
				</div>
			</div>
		</div>
	</div>
<% end %>

<br>

app/views/content_types/new.html.erb
<h2>Add a Content Type</h2>

<p><strong>Types</strong> are used to group content together and provide a parent for Levels.</p>

<%= render 'form' %>

app/views/content_types/show.html.erb
<div class="content-actions pull-right">

	<%= link_to "Add Topic", new_topic_path(:content_type_id => @content_type.id), class: 'btn' %>
	<%= link_to 'Add Content Level', new_content_level_path, class: 'btn' %>
	<%= link_to 'Edit Content Type', edit_content_type_path(@content_type), class: 'btn' %>
	
	<br>
	<%= link_to 'Delete Type', @content_type, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger absolute-button' %>
	

</div>

<h2 class="page-header"><%= @content_type.name %></h2>
<p class="text-muted">
  <%= @content_type.description %>
</p>

<div class="row">
<!--
	<div class="col-sm-12">
		<h4 class="section-header">Levels</h4>
		<% ContentLevel.where(:content_type_level_id => @content_type.id).each do |cl| %>
		<p><%= link_to cl.name, content_level_path(cl) %></p>
		<% end %>
	</div>
-->
	
	<div class="col-sm-12">
		<h4 class="section-header">Topics</h4>
		<% @content_type.topics.each do |topic| %>
		<div class="panel-body">
			<p><strong><%= link_to topic.name, topic_path(topic) %></strong></p>
			<p><%= link_to "Edit", edit_topic_path(topic) %></p>
		</div>
		<% end %>
	</div>

</div>






<div id="modal-window" class="modal hide fade" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true"></div>