config/routes.rb
Rails.application.routes.draw do
  resources :topics
  resources :content_levels
  resources :content_types
  root 'dashboard#index'
  
  devise_for :users
  
	get 'explorer' => 'dashboard#explorer'
	get 'change_user_level' => 'dashboard#change_user_level'
	
	post 'set_user_level' => 'content_levels#set_user_level_setting', as: 'set_user_level'
  
  

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#sidebar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
          <a class="navbar-brand" href="<%= root_path %>"><span>flat</span>iron</a>
            <ul class="user-menu">
                <li class="dropdown pull-right">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><svg class="glyph stroked male-user"><use xlink:href="#stroked-male-user"></use></svg> User <span class="caret"></span></a>
                    <ul class="dropdown-menu" role="menu">
                        <li><a href="#"><svg class="glyph stroked male-user"><use xlink:href="#stroked-male-user"></use></svg> Profile</a></li>
                        <li><a href="#"><svg class="glyph stroked gear"><use xlink:href="#stroked-gear"></use></svg> Settings</a></li>
                        <% if user_signed_in? %>
                          <li><%= link_to('<svg class="glyph stroked cancel"><use xlink:href="#stroked-cancel"></use></svg> Logout'.html_safe, destroy_user_session_path, :method => :delete) %></li>
                        <% else %>
                          <%= link_to('Login', new_user_session_path)  %>  
                        <% end %>
                    </ul>
                </li>
            </ul>
        </div>

    </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_notifications.html.erb
<div class="notifications">
	<% if notice %>
		<div class="alert alert-info notice">
			<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
			<%= notice %>
		</div>
	<% end %>
	<% if alert %>
		<div class="alert alert-danger">
			<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
			<%= alert %>
		</div>
	<% end %>
</div>

app/views/layouts/_sidebar.html.erb
<div id="sidebar-collapse" class="col-sm-3 col-lg-2 sidebar">
    <form role="search">
        <div class="form-group">
			<p>Content Engine</p>
<!--            <input type="text" class="form-control" placeholder="Search">-->
        </div>
    </form>
    <ul class="nav menu">
        <!--<li><%= link_to '<svg class="glyph stroked dashboard-dial"><use xlink:href="#stroked-dashboard-dial"></use></svg> Dashboard'.html_safe, root_path %></li>-->
		<li><%= link_to '<svg class="glyph stroked map"><use xlink:href="#stroked-map"/></svg> Explorer'.html_safe, explorer_path %></li>
		<li><%= link_to '<svg class="glyph stroked table"><use xlink:href="#stroked-table"/></svg> Content Levels'.html_safe, content_levels_path %></li>
		<li><%= link_to '<svg class="glyph stroked blank document"><use xlink:href="#stroked-blank-document"/></svg> Content Types'.html_safe, content_types_path %></li>
		<li><%= link_to '<svg class="glyph stroked pen tip"><use xlink:href="#stroked-pen-tip"/></svg> Topics'.html_safe, topics_path %></li>
<!--
        <li class="parent ">
            <a href="#">
                <span data-toggle="collapse" href="#sub-item-1"><svg class="glyph stroked chevron-down"><use xlink:href="#stroked-chevron-down"></use></svg></span> Dropdown 
            </a>
            <ul class="children collapse" id="sub-item-1">
                <li>
                    <a class="" href="#">
                        <svg class="glyph stroked chevron-right"><use xlink:href="#stroked-chevron-right"></use></svg> Sub Item 1
                    </a>
                </li>
                <li>
                    <a class="" href="#">
                        <svg class="glyph stroked chevron-right"><use xlink:href="#stroked-chevron-right"></use></svg> Sub Item 2
                    </a>
                </li>
                <li>
                    <a class="" href="#">
                        <svg class="glyph stroked chevron-right"><use xlink:href="#stroked-chevron-right"></use></svg> Sub Item 3
                    </a>
                </li>
            </ul>
        </li>
-->
        <li role="presentation" class="divider"></li>
		<% if user_signed_in? %>
		  <li><%= link_to('<svg class="glyph stroked cancel"><use xlink:href="#stroked-cancel"></use></svg> Logout'.html_safe, destroy_user_session_path, :method => :delete) %></li>
		<% else %>
		  <%= link_to('<svg class="glyph stroked male-user"><use xlink:href="#stroked-male-user"></use></svg> Login'.html_safe, new_user_session_path) %>  
		<% end %>
    </ul>

</div><!--/.sidebar-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Flatiron</title>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css">
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%= csrf_meta_tags %>
</head>
<body>
	<% if user_signed_in? %>
		<%= render 'layouts/header' %>
		<%= render 'layouts/sidebar' %>
	<% else %>
	<% end %>

	<% if user_signed_in? %>
		<div class="col-sm-9 col-sm-offset-3 col-lg-10 col-lg-offset-2 main">
			<%= render 'layouts/notifications' %>
			<%= yield %>
		</div>
	<% else %>
		<div class="col-sm-10 col-sm-offset-1">
			<%= yield %>
		</div>
	<% end %>

</body>
</html>